### ISSUE TITLE
[semantic conventions] protect against duplicated briefs/notes

### ISSUE THREAD

**Issue by Sherlouk** [open-telemetry/build-tools#39]
A mistake was fixed in [spec#1595](https://github.com/open-telemetry/opentelemetry-specification/pull/1595) in which it was spotted that the exact same brief was used, incorrectly, by multiple attributes.

I believe a warning/error should be introduced to the tooling to spot duplications like this in either the `brief` or `note` value.

**Comment by lmolkova** [comment]
this kind of issues should be caught with the code review rather than tooling. We can detect exact matches, but exact match does not always indicate any problem. Tooling would produce a lot of false negatives and won't catch anything beyond exact match.

I'm going to close this one, feel free to reopen if you believe a reliable and useful check can be created.
